# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: invertebrate // powerviolence // grindcore // hate
email: dkmkelley@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Invertebrate is a 3-piece band based in Oakland, CA.  We play a mix of
  powerviolence, grindcore, and sludge music.  We hate pretty much everything.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: dkmkelley
github_username:  dkmkelley

# Build settings
markdown: kramdown
